language: php

php:
  - 5.6
  - 7.1

install:
  - composer self-update
  - composer install

services:
  - mysql

env: DB_USER=travis

before_script:
  - echo 'date.timezone = "Europe/London"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e 'CREATE DATABASE `test_media_felix`;'

script: vendor/bin/phpunit tests

notifications:
  irc:
    channels:
      - "chat.freenode.net#felixonline"
    on_success: change
    skip_join: true
    on_failure: always
