<?php
namespace FelixOnline\Core;

// THIS FILE IS AUTOMATICALLY GENERATED
// To modify, use the Model Builder located in the "build" directory.

use FelixOnline\Base\BaseDB;
use FelixOnline\Base\BaseManager;
use FelixOnline\Base\Type;
use FelixOnline\Base\App;
use FelixOnline\Exceptions\InternalException;

/**
 * Individual publications for issue archive PDFs to reside in (e.g. Felix, Phoenix).
 *
 * Fields:
 * - name: (CharField) Name of publication.
 * - inactive: (BooleanField) Publication is inactive (hide issues within it, and prevent new issues in publication).
 * - id: (IntegerField) this primary key is automatically added by the database layer.
 * - deleted: (BooleanField) this indicates if the database layer should not load this record (soft deletion) and this field is automatically added by the database layer.
 *
 * @author Philip Kent <philip.kent@me.com>
 * @license BSD
 * @codeCoverageIgnore
 */
class ArchivePublication extends BaseDB
{
    /**
     * @var char $dbtable Table to reference.
     */
    public $dbtable = 'archive_publication';

    /**
     * Constructor: prepares a new instance of this model.
     *
     * @param int $id If specified, fetch record with this primary key from the database. If not specified, a new empty record is generated.
     *
     * @throws FelixOnline\Exceptions\InternalException if definition is incorrectly configured.
     * @throws FelixOnline\Exceptions\ModelNotFoundException if primary key specified and the associated record has been deleted or is not present.
     */
    public function __construct($id = null)
    {
        $fields = array(
            'name' => new Type\CharField(),
            'inactive' => new Type\BooleanField(),
        );

        parent::__construct($fields, $id, null, false);
    }
}
