<?php
namespace FelixOnline\Core;

// THIS FILE IS AUTOMATICALLY GENERATED
// To modify, use the Model Builder located in the "build" directory.

use FelixOnline\Base\BaseDB;
use FelixOnline\Base\BaseManager;
use FelixOnline\Base\Type;
use FelixOnline\Base\App;
use FelixOnline\Exceptions\InternalException;

/**
 * Options for comment posting permissions on articles. Option definition table for Admin interface.
 *
 * Fields:
 * - description: (CharField) Option description as defined in the class constants.
 * - id: (IntegerField) this primary key is automatically added by the database layer.
 * - deleted: (BooleanField) this indicates if the database layer should not load this record (soft deletion) and this field is automatically added by the database layer.
 *
 * @author Philip Kent <philip.kent@me.com>
 * @license BSD
 * @codeCoverageIgnore
 */
class ArticleCommentStatus extends BaseDB
{
    /**
     * @var char $dbtable Table to reference.
     */
    public $dbtable = 'article_comment_status';

    /**
     * @var int ARTICLE_COMMENTS_OFF Article does not allow comments.
     */
    const ARTICLE_COMMENTS_OFF = 0;

    /**
     * @var int ARTICLE_COMMENTS_ON Article allows comments.
     */
    const ARTICLE_COMMENTS_ON = 1;

    /**
     * @var int ARTICLE_COMMENTS_INTERNAL Article only allows comments from users on the internal network.
     */
    const ARTICLE_COMMENTS_INTERNAL = 2;


    /**
     * Constructor: prepares a new instance of this model.
     *
     * @param int $id If specified, fetch record with this primary key from the database. If not specified, a new empty record is generated.
     *
     * @throws FelixOnline\Exceptions\InternalException if definition is incorrectly configured.
     * @throws FelixOnline\Exceptions\ModelNotFoundException if primary key specified and the associated record has been deleted or is not present.
     */
    public function __construct($id = null)
    {
        $fields = array(
            'description' => new Type\CharField(),
        );

        parent::__construct($fields, $id, null, false);
    }
}
