<?php
namespace FelixOnline\Core;

// THIS FILE IS AUTOMATICALLY GENERATED
// To modify, use the Model Builder located in the "build" directory.

use FelixOnline\Base\BaseDB;
use FelixOnline\Base\BaseManager;
use FelixOnline\Base\Type;
use FelixOnline\Base\App;
use FelixOnline\Exceptions\InternalException;

/**
 * Table to allocate articles to featured article sections on the front page.
 *
 * Fields:
 * - article: (ForeignKey) ID number of article.
 * - section: (CharField) Reference number for frontpage section.
 * @todo This should be in a more sensible format as it is not user-discoverable.
 * - sort_order: (IntegerField) Sort order for articles in the same section. Numbers closer to zero would be expected to be placed at the top of lists.
 * - id: (IntegerField) this primary key is automatically added by the database layer.
 * - deleted: (BooleanField) this indicates if the database layer should not load this record (soft deletion) and this field is automatically added by the database layer.
 *
 * @author Philip Kent <philip.kent@me.com>
 * @license BSD
 * @codeCoverageIgnore
 */
class Frontpage extends BaseDB
{
    /**
     * @var char $dbtable Table to reference.
     */
    public $dbtable = 'frontpage';

    /**
     * Constructor: prepares a new instance of this model.
     *
     * @param int $id If specified, fetch record with this primary key from the database. If not specified, a new empty record is generated.
     *
     * @throws FelixOnline\Exceptions\InternalException if definition is incorrectly configured.
     * @throws FelixOnline\Exceptions\ModelNotFoundException if primary key specified and the associated record has been deleted or is not present.
     */
    public function __construct($id = null)
    {
        $fields = array(
            'article' => new Type\ForeignKey('FelixOnline\Core\Article'),
            'section' => new Type\CharField(),
            'sort_order' => new Type\IntegerField(),
        );

        parent::__construct($fields, $id, null, false);
    }
}
