<?php
namespace FelixOnline\Core;

// THIS FILE IS AUTOMATICALLY GENERATED
// To modify, use the Model Builder located in the "build" directory.

use FelixOnline\Base\BaseDB;
use FelixOnline\Base\BaseManager;
use FelixOnline\Base\Type;
use FelixOnline\Base\App;
use FelixOnline\Exceptions\InternalException;

/**
 * Redirection URL (short link) definitions.
 *
 * Fields:
 * - link: (CharField) Short link reference (entered by users).
 * - url: (CharField) URL for link to redirect to.
 * - active: (BooleanField) Flag for whether this link redirection be active.
 * - deleted: (BooleanField) this indicates if the database layer should not load this record (soft deletion) and this field is automatically added by the database layer.
 *
 * @author Philip Kent <philip.kent@me.com>
 * @license BSD
 * @codeCoverageIgnore
 */
class Link extends BaseDB
{
    /**
     * @var char $dbtable Table to reference.
     */
    public $dbtable = 'link';

    /**
     * Constructor: prepares a new instance of this model.
     *
     * @param char $link If specified, fetch record with this primary key from the database. If not specified, a new empty record is generated.
     *
     * @throws FelixOnline\Exceptions\InternalException if definition is incorrectly configured.
     * @throws FelixOnline\Exceptions\ModelNotFoundException if primary key specified and the associated record has been deleted or is not present.
     */
    public function __construct($link = null)
    {
        $fields = array(
            'link' => new Type\CharField(array(
                "primary" => true,
            )),
            'url' => new Type\CharField(),
            'active' => new Type\BooleanField(),
        );

        parent::__construct($fields, $id, null, false);
    }
}
