<?php
namespace FelixOnline\Core;

// THIS FILE IS AUTOMATICALLY GENERATED
// To modify, use the Model Builder located in the "build" directory.

use FelixOnline\Base\BaseDB;
use FelixOnline\Base\BaseManager;
use FelixOnline\Base\Type;
use FelixOnline\Base\App;
use FelixOnline\Exceptions\InternalException;

/**
 * Responses to individual polls.
 *
 * Fields:
 * - poll: (ForeignKey) ID number of poll.
 * - option: (ForeignKey) ID number of poll option.
 * - ip: (TextField) IP address of respondee to prevent multiple voting.
 * @todo use of TextField is inefficient.
 * - useragent: (TextField) User agent of respondee to prevent multiple voting.
 * @todo use of TextField is inefficient.
 * - id: (IntegerField) this primary key is automatically added by the database layer.
 * - deleted: (BooleanField) this indicates if the database layer should not load this record (soft deletion) and this field is automatically added by the database layer.
 *
 * @author Philip Kent <philip.kent@me.com>
 * @license BSD
 * @codeCoverageIgnore
 */
class PollResponse extends BaseDB
{
    /**
     * @var char $dbtable Table to reference.
     */
    public $dbtable = 'polls_response';

    /**
     * Constructor: prepares a new instance of this model.
     *
     * @param int $id If specified, fetch record with this primary key from the database. If not specified, a new empty record is generated.
     *
     * @throws FelixOnline\Exceptions\InternalException if definition is incorrectly configured.
     * @throws FelixOnline\Exceptions\ModelNotFoundException if primary key specified and the associated record has been deleted or is not present.
     */
    public function __construct($id = null)
    {
        $fields = array(
            'poll' => new Type\ForeignKey('FelixOnline\Core\Poll'),
            'option' => new Type\ForeignKey('FelixOnline\Core\PollOption'),
            'ip' => new Type\TextField(),
            'useragent' => new Type\TextField(),
        );

        parent::__construct($fields, $id, null, true);
    }
}
