<?php
namespace FelixOnline\Core;

// THIS FILE IS AUTOMATICALLY GENERATED
// To modify, use the Model Builder located in the "build" directory.

use FelixOnline\Base\BaseDB;
use FelixOnline\Base\BaseManager;
use FelixOnline\Base\Type;
use FelixOnline\Base\App;
use FelixOnline\Exceptions\InternalException;

/**
 * Location of poll on an article page. Option definition table for Admin interface.
 *
 * Fields:
 * - description: (CharField) Option description as defined in the class constants.
 * - id: (IntegerField) this primary key is automatically added by the database layer.
 * - deleted: (BooleanField) this indicates if the database layer should not load this record (soft deletion) and this field is automatically added by the database layer.
 *
 * @author Philip Kent <philip.kent@me.com>
 * @license BSD
 * @codeCoverageIgnore
 */
class PollLocation extends BaseDB
{
    /**
     * @var char $dbtable Table to reference.
     */
    public $dbtable = 'polls_location';

    /**
     * @var int POLL_BOTTOM Poll appears at the bottom of the article only.
     */
    const POLL_BOTTOM = 0;

    /**
     * @var int POLL_TOP Poll appears at the top of the article only.
     */
    const POLL_TOP = 1;

    /**
     * @var int POLL_BOTH Poll appears at the top and bottom of the article.
     */
    const POLL_BOTH = 2;


    /**
     * Constructor: prepares a new instance of this model.
     *
     * @param int $id If specified, fetch record with this primary key from the database. If not specified, a new empty record is generated.
     *
     * @throws FelixOnline\Exceptions\InternalException if definition is incorrectly configured.
     * @throws FelixOnline\Exceptions\ModelNotFoundException if primary key specified and the associated record has been deleted or is not present.
     */
    public function __construct($id = null)
    {
        $fields = array(
            'description' => new Type\CharField(),
        );

        parent::__construct($fields, $id, null, false);
    }
}
