<?php
namespace FelixOnline\Core;

// THIS FILE IS AUTOMATICALLY GENERATED
// To modify, use the Model Builder located in the "build" directory.

use FelixOnline\Base\BaseDB;
use FelixOnline\Base\BaseManager;
use FelixOnline\Base\Type;
use FelixOnline\Base\App;
use FelixOnline\Exceptions\InternalException;

/**
 * Article text bodies.
 *
 * Fields:
 * - user: (ForeignKey) User name of individual who wrote article text.
 * - content: (TextField) Article text body in Sir Trevor JSON/Markdown format.
 * - timestamp: (DateTimeField) Date and time the article body was created.
 * - converted: (BooleanField) Flag to indicate the text was converted from HTML to JSON/Markdown format. Should always be 1 for new records.
 * - id: (IntegerField) this primary key is automatically added by the database layer.
 * - deleted: (BooleanField) this indicates if the database layer should not load this record (soft deletion) and this field is automatically added by the database layer.
 *
 * @author Philip Kent <philip.kent@me.com>
 * @license BSD
 * @codeCoverageIgnore
 */
class Text extends BaseDB
{
    /**
     * @var char $dbtable Table to reference.
     */
    public $dbtable = 'text_story';

    /**
     * Constructor: prepares a new instance of this model.
     *
     * @param int $id If specified, fetch record with this primary key from the database. If not specified, a new empty record is generated.
     *
     * @throws FelixOnline\Exceptions\InternalException if definition is incorrectly configured.
     * @throws FelixOnline\Exceptions\ModelNotFoundException if primary key specified and the associated record has been deleted or is not present.
     */
    public function __construct($id = null)
    {
        $fields = array(
            'user' => new Type\ForeignKey('FelixOnline\Core\User'),
            'content' => new Type\TextField(),
            'timestamp' => new Type\DateTimeField(),
            'converted' => new Type\BooleanField(),
        );

        parent::__construct($fields, $id, null, false);
    }
}
